### ISSUE TITLE
Many to many video chats

### ISSUE THREAD

**Issue by dkrusenstrahle** [skyllo/peer-lite#1]
Hello,

Do this library support many to many video chats?

Thank you!

**Comment by skyllo** [comment]
Hey!

Apologies for the long response time, I totally missed this. No, this does not support many-to-many connections however you could connect each peer to every other peer but that's quite inefficient. I think the best way to implement many-to-many is use a WebRTC media server, though I have never tried that!

Hope this helps, thanks!
