### ISSUE TITLE
Question: can I use it on server?

### ISSUE THREAD

**Issue by slavaGanzin** [skyllo/peer-lite#33]
Hello, Nick.

Awesome library, thank for your work. I need to record videos between two parties, or even just stream video stream to server. It this possible? Or maybe you know the way to do it? I'm really new to WebRTC, so maybe you could help with an advice?

Thanks in advance

**Comment by skyllo** [comment]
Thanks! Sorry I've never worked on recording WebRTC streams or streaming to the server before. It's difficult enough in the browser! I wish I was able to help more, I hope you find a good solution :)
